title: readhop
name: readhop
description: Read, one hop at a time.
github: [metadata]
highlighter: rouge
theme: jekyll-theme-primer
url: "https://readhop.com"
google_analytics: UA-158033435-1
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag