title: readhop
name: readhop
description: Read, one hop at a time.
github: [metadata]
theme: jekyll-theme-primer
url: "https://readhop.com"
google_analytics: UA-158033435-1
feed:
  excerpt_only: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-target-blank