title: readhop
name: readhop
description: Read, one hop at a time.
github: [metadata]
highlighter: rouge
theme: minima
url: "https://readhop.com"
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag